export const languageOptions = [
  { value: "en", label: "English", flag: "🇬🇧" },
  { value: "es", label: "Spanish", flag: "🇪🇸" },
  { value: "fr", label: "French", flag: "🇫🇷" },
  { value: "de", label: "German", flag: "🇩🇪" },
  { value: "it", label: "Italian", flag: "🇮🇹" },
  { value: "pt", label: "Portuguese", flag: "🇵🇹" },
  { value: "ru", label: "Russian", flag: "🇷🇺" },
  { value: "zh", label: "Chinese", flag: "🇨🇳" },
  { value: "ja", label: "Japanese", flag: "🇯🇵" },
  { value: "ko", label: "Korean", flag: "🇰🇷" },
  { value: "ar", label: "Arabic", flag: "🇸🇦" },
  { value: "hi", label: "Hindi", flag: "🇮🇳" },
  { value: "bn", label: "Bengali", flag: "🇧🇩" },
  { value: "id", label: "Indonesian", flag: "🇮🇩" },
  { value: "tr", label: "Turkish", flag: "🇹🇷" },
  { value: "th", label: "Thai", flag: "🇹🇭" },
  { value: "vi", label: "Vietlabelse", flag: "🇻🇳" },
  { value: "nl", label: "Dutch", flag: "🇳🇱" },
  { value: "pl", label: "Polish", flag: "🇵🇱" },
  { value: "sv", label: "Swedish", flag: "🇸🇪" },
  {
    value: "ph",
    label: "Philippines",
    flag: "🇵🇭",
  },
  {
    value: "ms",
    label: "Malaysia",
    flag: "🇲🇾",
  },
];
