import { TemplateDatas } from "@/lib/Context";
export const defaultTemplateDatas: TemplateDatas = {
  TemplateOne: {
    // "Construction Site","Clock in to work" ,"Recording Every Minute of Your Life"
    screenData: {
      en: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Traffic accident",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Construction Site",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          // {
          //   name: "subtitle",
          //   font: {
          //     color: "#fff",
          //     size: 16,
          //     weight: "normal",
          //     family: "Palatino",
          //     bold: true,
          //     italic: false,
          //     underline: false,
          //     align: "center",
          //   },
          //   value: "Stand out from the crowd.",
          //   zIndex: 1,
          //   box: {
          //     x: 0,
          //     y: 100,
          //     w: "100%",
          //     h: 100,
          //   },
          //   type: "text",
          // },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Clock in to work",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Recording Every ",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Minute of Your Life",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],
      cn: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "交通事故现场",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "工地现场",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "工作时钟",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "记录你",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "生活的每一分钟",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],
    },
    arrow: true,
    bg: "",
    bgColor: "#c084fc",
    primaryColor: "#fff",
  },
};
