import { TemplateDatas } from "@/lib/Context";
export const defaultTemplateDatas: TemplateDatas = {
  TemplateOne: {
    screenData: {
      //       Traffic accident: tai nạn giao thông
      // Construction site: công trường xây dựng
      // Clock in to work: chấm công
      // Recording every minute of your life: ghi lại từng phút giây của cuộc sống
      vn: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "tai nạn giao thông",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "công trường xây dựng",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          // {
          //   name: "subtitle",
          //   font: {
          //     color: "#fff",
          //     size: 16,
          //     weight: "normal",
          //     family: "Palatino",
          //     bold: true,
          //     italic: false,
          //     underline: false,
          //     align: "center",
          //   },
          //   value: "Stand out from the crowd.",
          //   zIndex: 1,
          //   box: {
          //     x: 0,
          //     y: 100,
          //     w: "100%",
          //     h: 100,
          //   },
          //   type: "text",
          // },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "chấm công",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "ghi lại từng phút",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "giây của cuộc sống",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],

      // Indonesian
      // Traffic accident: kecelakaan lalu lintas
      // Construction site: lokasi pembangunan
      // Clock in to work: absen masuk kerja
      // Recording every minute of your life: merekam setiap menit hidup Anda
      id: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "kecelakaan lalu lintas",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "lokasi pembangunan",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          // {
          //   name: "subtitle",
          //   font: {
          //     color: "#fff",
          //     size: 16,
          //     weight: "normal",
          //     family: "Palatino",
          //     bold: true,
          //     italic: false,
          //     underline: false,
          //     align: "center",
          //   },
          //   value: "Stand out from the crowd.",
          //   zIndex: 1,
          //   box: {
          //     x: 0,
          //     y: 100,
          //     w: "100%",
          //     h: 100,
          //   },
          //   type: "text",
          // },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "absen masuk kerja",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "merekam setiap",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "menit hidup Anda",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],
      //       Traffic accident: aksidente sa trapiko
      // Construction site: lugar ng konstruksiyon
      // Clock in to work: mag-time in sa trabaho
      // Recording every minute of your life: nagre-record ng bawat minuto ng buhay mo
      ph: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "aksidente sa trapiko",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 22,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "lugar ng konstruksiyon",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          // {
          //   name: "subtitle",
          //   font: {
          //     color: "#fff",
          //     size: 16,
          //     weight: "normal",
          //     family: "Palatino",
          //     bold: true,
          //     italic: false,
          //     underline: false,
          //     align: "center",
          //   },
          //   value: "Stand out from the crowd.",
          //   zIndex: 1,
          //   box: {
          //     x: 0,
          //     y: 100,
          //     w: "100%",
          //     h: 100,
          //   },
          //   type: "text",
          // },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 22,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "mag-time in sa trabaho",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "nagre-record ng bawat",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "minuto ng buhay mo",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],
      en: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Traffic accident",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Construction Site",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          // {
          //   name: "subtitle",
          //   font: {
          //     color: "#fff",
          //     size: 16,
          //     weight: "normal",
          //     family: "Palatino",
          //     bold: true,
          //     italic: false,
          //     underline: false,
          //     align: "center",
          //   },
          //   value: "Stand out from the crowd.",
          //   zIndex: 1,
          //   box: {
          //     x: 0,
          //     y: 100,
          //     w: "100%",
          //     h: 100,
          //   },
          //   type: "text",
          // },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Clock in to work",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Recording Every ",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "Minute of Your Life",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],
      cn: [
        [
          {
            name: "title",
            font: {
              color: "#fff",
              size: 24,
              family: "Palatino",
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "交通事故现场",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "工地现场",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 24,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "工作时钟",
            box: {
              x: 0,
              y: 40,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
        [
          {
            name: "title",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "记录你",
            box: {
              x: 0,
              y: 20,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },
          {
            name: "title1",
            font: {
              family: "Palatino",
              color: "#fff",
              size: 20,
              weight: "normal",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "生活的每一分钟",
            box: {
              x: 0,
              y: 50,
              w: "100%",
              h: 100,
            },
            type: "text",
            zIndex: 1,
          },

          {
            name: "banner",
            font: {
              color: "#fff",
              size: 24,
              weight: "normal",
              family: "Arial",
              bold: true,
              italic: false,
              underline: false,
              align: "center",
            },
            value: "./ios.jpg",
            box: {
              x: (248 - 156) / 2,
              y: 100,
              w: 156,
              h: 312,
            },
            type: "image",
            zIndex: 0,
          },
        ],
      ],
    },
    arrow: true,
    bg: "",
    bgColor: "#c084fc",
    primaryColor: "#fff",
  },
};
